### ISSUE TITLE
Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by arg3t** [hyplabs/femtoshare#1]
There is a directory traversal vunerability in the code. The  attacker can access sstem files such as /etc/passwd by using double dots such as: /../../......../etc/passwd

**Comment by yigitcolakoglu** [comment]
#

**Comment by yigitcolakoglu** [comment]
#2

**Comment by arg3t** [comment]
Fixed the issue as well as a bug with --files-dir option.
#2 
Great project, the only thing I can find that looks good and is actually simple. Wish more people heard of this project.

**Comment by Uberi** [comment]
Hey @yigitcolakoglu,

Glad you like femtoshare, and great catch! Do you have an example of the directory traversal in action? I think there were a few checks already in that `is_valid_filename` function, but maybe there's something missing? Either way, I'd be happy to review and merge your PR.

**Comment by Uberi** [comment]
Merged!
